### ISSUE TITLE
Re-adjust health-related values to make more sense

### ISSUE THREAD

**Issue by bseibo61** [bseibo61/Tingo#44]
In the unity script Feed, there are a few values that determine the rate that the Tingo gets berries, gets XP, and looses health.  XP is calculated by the total number of steps that have been taken with the current Tingo.  Currently, nobody has gone through the math and figured out good rates for these, where the Tingo can get enough berries to spend on staying alive, but doesn't end up with a massive surplus of berries.  In the Unity script Menu, there is a variable that determines how many steps are needed to level up.  Here are some of the values that need to be adjusted.  

- Health Drain
- How much berries increase the health by
-  How many steps are equal to XP

Just to clarify, the Tingo's health drains every hour, and the only way to fill it is to earn berries.  Once a certain amount of XP is collected, the Tingo can level up.

If there are any questions about this issue, look over the documentation and feel free to contact team Tingo through Gitter.

**Comment by zhaosec** [comment]
Sorry, I am not sure how to play this game. As stated in MVP, the tingo can be controlled by the voice input. But it can only understand "JUMP" as far as I know. Also, what is XP, health mean?

**Comment by jonhiggins15** [comment]
Please watch our beta video to help further understand what the Tingo can do https://www.youtube.com/watch?v=jUQiTgDmenQ

**Comment by bseibo61** [comment]
Our landing page also explains more of the health/XP functionality.  The voice input is based on sentiment analysis, so if you tell the Tingo something positive, it will react positively and if you tell it something negative, it will react negatively.  If you have any further questions, feel free to contact us through our Gitter.  Thanks!
