### ISSUE TITLE
Re-adjust flipping to normalize flips

### ISSUE THREAD

**Issue by jonhiggins15** [bseibo61/Tingo#49]
Currently, there is an addon that we are using in Unity called "iTween". This allows for easier movement and animations for the Tingo. Right now we have the Tingo jump, flip, and speak when told to via voice recognition. Jump and speak work but flip causes it to flip under the floor in a weird way, then when it is said again it flips back to a normal position. 
For fixing the issue here are some values and functions that may need to be adjusted:

- iTween.RotateBy in the testSpeach 

- Flip function in testSpeach 

-  the z value is RotateBy may affect the way it flips

Just to clarify, when the user first says "flip" the Tingo flips in an odd way and ends up upside down and under the floor. When the user says "flip" a second time, it flips back to a normal position. 

If there are any questions about this issue, look over the documentation and feel free to contact team Tingo through Gitter.

**Comment by jwreimer** [comment]
I look forward to being able to help with this issue!
