### ISSUE TITLE
Tingo got stuck in the air when performing jump command near the table

### ISSUE THREAD

**Issue by KimDoggy** [bseibo61/Tingo#74]
As the title suggests, Tingo will get stuck in the air when performing the jump command near the table. It never comes back to the floor. I have to exit the application and come back in for it to land on the floor. 

![screenshot_20180416-120903](https://user-images.githubusercontent.com/29526851/38821746-698356a4-416f-11e8-9d9d-a0f69e42490f.jpg)

**Comment by jonhiggins15** [comment]
Thank you for the bug report
