### ISSUE TITLE
Right wall is missing.

### ISSUE THREAD

**Issue by CheezedFish** [bseibo61/Tingo#78]
Though it seems inconsequential, with the furniture physics this can become an issue. After knocking down the bookcase by flipping into it, I got my Tingo to the other side of the bookcase in order to push it to the right side of the screen. After doing so, the table eventually fell off the map from the right side. Perhaps putting an invisible wall here might work instead of doing a visible wall?

**Comment by CheezedFish** [comment]
https://imgur.com/a/7Ed2p
See image for result

**Comment by jonhiggins15** [comment]
Currently, we are changing the way that the Tingo will interact with the furniture around the room. This should ensure that the bookcase and table will no longer be able to be pushed out of the room. Thank you for your feedback and making Tingo better!
