### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jniyomugabo** [bseibo61/Tingo#89]
Tingo would speak when she is not even commanded to speak

**Comment by jonhiggins15** [comment]
I believe that you are referencing the sounds it makes when other actions are asked for (like jump). This is a feature

**Comment by jniyomugabo** [comment]
for example, I would say something like run or spin or but without mentioning speak, it would randomly speak. I thought It would only speak when commanded to but might be it makes those sounds even when other actions are asked which I probably wasn't ware.

Also, the steps count did not work on android LG tablet with wifi and cellular network access

**Comment by bseibo61** [comment]
We believe the Tingo should be vocal, to seem more likable.  This is why we decided to make the Tingo speak when the user tells it to jump or spin, or any other command.  This also works as feedback for the user.  

For the steps issue, we need an accelerator in the phone to measure leg movements to measure steps.  Many tablets do not have these so there is no way to measure steps.

Thanks for the bug report, these are what help us make Tingo better.
